name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - 'v*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker build -t ghcr.io/${{ github.repository }}:$TAG .
        
      - name: Push Docker Image to GHCR
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker push ghcr.io/${{ github.repository }}:$TAG
