name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - 'v*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout پروژه
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

#      # Log in to GitHub Container Registry (GHCR)
#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker Image with tag from Git tag
      - name: Build Docker Image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker build -t ghcr.io/${{ github.repository }}:$TAG .
        
      # Push Docker Image to GHCR
      - name: Push Docker Image to GHCR
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker push ghcr.io/${{ github.repository }}:$TAG
